name: Docker
on: [push]

jobs:
  build:
    name: Documentation build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Build documentation
        run: make

      - uses: actions/upload-artifact@master
        with:
          name: docs
          path: docs/

      - name: Create zip file with documentation
        if: startsWith(github.ref, 'refs/tags/v')
        run: zip -r docs.zip docs/

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          prerelease: true
          files: docs.zip
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
